print('Olá me diga 2 números e irei somar ambos !')
num1 = int(input('Diga-me o primeiro número = '))
num2 = int(input('Diga-me o segundo número = '))
soma = (num1 + num2)
print('Voltei a soma de {} e {} é {}'.format(num1, num2, soma))
