algo = input('Digite algo !: ')
print('Você digitou :'.format(algo))
print('O tipo primitivo desse valor é :', type(algo))
print('Só tem espaços ? :', algo.isspace())
print('É um número ? :', algo.isnumeric())
print('É alfabetico ?:', algo.isalpha())
print('É um decimal ?:', algo.isdecimal())
print('É um alfanumérico ?:', algo.isalnum())
print('Está maiusculo ?:', algo.isupper())
print('Está minusculo ?:', algo.islower())
